name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Install libgtk-3-dev
        run: sudo apt-get install libgtk-3-dev

      - name: Build
        run: cargo build --all --release

      - name: Test
        run: cargo test --workspace